### ISSUE TITLE
Agnet

### ISSUE THREAD

**Issue by xiaobh1519** [Thinklab-SJTU/Bench2DriveZoo#14]
How can I generate Agent like this：https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/vad_b2d_agent.py

**Comment by jiaxiaosong1002** [comment]
@xiaobh1519 Agent code includes the preprocessing of input to feed into your neural network and the postprocess of your network output to control the vehicle.

**Comment by xiaobh1519** [comment]
> @xiaobh1519 Agent code includes the preprocessing of input to feed into your neural network and the postprocess of your network output to control the vehicle.

OK！Thanks
