### ISSUE TITLE
agent crashed

### ISSUE THREAD

**Issue by Huren900** [Thinklab-SJTU/Bench2DriveZoo#16]
every route would crashed at about ‘System time = 100’, can you help me?
`========= Preparing RouteScenario_2127 (repetition 0) =========
> Loading the world
> Setting up the agent
load checkpoint from path: /home/carla/Bench2DriveZoo/Bench2Drive/ckpts/VAD_tiny.pth
> Running the route
=== [Agent] -- Wallclock = 2024-07-24 08:18:52.119 -- System time = 0.000 -- Game time = 0.050 -- Ratio = 0.000x
=== [Agent] -- Wallclock = 2024-07-24 08:18:53.775 -- System time = 1.655 -- Game time = 0.100 -- Ratio = 0.060x
=== [Agent] -- Wallclock = 2024-07-24 08:18:55.079 -- System time = 2.960 -- Game time = 0.150 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:18:56.055 -- System time = 3.936 -- Game time = 0.200 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:18:56.992 -- System time = 4.872 -- Game time = 0.250 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:18:57.987 -- System time = 5.868 -- Game time = 0.300 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:18:58.927 -- System time = 6.808 -- Game time = 0.350 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:18:59.905 -- System time = 7.786 -- Game time = 0.400 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:19:00.902 -- System time = 8.783 -- Game time = 0.450 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:19:01.839 -- System time = 9.720 -- Game time = 0.500 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:19:02.817 -- System time = 10.698 -- Game time = 0.550 -- Ratio = 0.051x
=== [Agent] -- Wallclock = 2024-07-24 08:19:04.682 -- System time = 12.563 -- Game time = 0.600 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:06.535 -- System time = 14.416 -- Game time = 0.650 -- Ratio = 0.045x
=== [Agent] -- Wallclock = 2024-07-24 08:19:07.486 -- System time = 15.366 -- Game time = 0.700 -- Ratio = 0.046x
=== [Agent] -- Wallclock = 2024-07-24 08:19:08.403 -- System time = 16.284 -- Game time = 0.750 -- Ratio = 0.046x
=== [Agent] -- Wallclock = 2024-07-24 08:19:09.353 -- System time = 17.234 -- Game time = 0.800 -- Ratio = 0.046x
=== [Agent] -- Wallclock = 2024-07-24 08:19:10.279 -- System time = 18.160 -- Game time = 0.850 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:11.255 -- System time = 19.135 -- Game time = 0.900 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:12.197 -- System time = 20.078 -- Game time = 0.950 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:13.131 -- System time = 21.012 -- Game time = 1.000 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:14.071 -- System time = 21.952 -- Game time = 1.050 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:15.748 -- System time = 23.629 -- Game time = 1.100 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:16.706 -- System time = 24.586 -- Game time = 1.150 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:17.693 -- System time = 25.574 -- Game time = 1.200 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:18.675 -- System time = 26.556 -- Game time = 1.250 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:19.598 -- System time = 27.478 -- Game time = 1.300 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:20.515 -- System time = 28.396 -- Game time = 1.350 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:21.438 -- System time = 29.319 -- Game time = 1.400 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:22.547 -- System time = 30.428 -- Game time = 1.450 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:23.477 -- System time = 31.358 -- Game time = 1.500 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:24.412 -- System time = 32.293 -- Game time = 1.550 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:26.164 -- System time = 34.045 -- Game time = 1.600 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:27.127 -- System time = 35.008 -- Game time = 1.650 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:28.054 -- System time = 35.935 -- Game time = 1.700 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:28.996 -- System time = 36.877 -- Game time = 1.750 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:29.907 -- System time = 37.788 -- Game time = 1.800 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:30.818 -- System time = 38.698 -- Game time = 1.850 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:31.779 -- System time = 39.660 -- Game time = 1.900 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:32.786 -- System time = 40.667 -- Game time = 1.950 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:33.748 -- System time = 41.629 -- Game time = 2.000 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:34.744 -- System time = 42.624 -- Game time = 2.050 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:36.548 -- System time = 44.428 -- Game time = 2.100 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:37.448 -- System time = 45.328 -- Game time = 2.150 -- Ratio = 0.047x
=== [Agent] -- Wallclock = 2024-07-24 08:19:38.381 -- System time = 46.262 -- Game time = 2.200 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:39.329 -- System time = 47.210 -- Game time = 2.250 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:40.319 -- System time = 48.200 -- Game time = 2.300 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:41.236 -- System time = 49.116 -- Game time = 2.350 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:42.223 -- System time = 50.103 -- Game time = 2.400 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:43.161 -- System time = 51.042 -- Game time = 2.450 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:44.049 -- System time = 51.930 -- Game time = 2.500 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:45.076 -- System time = 52.957 -- Game time = 2.550 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:46.850 -- System time = 54.730 -- Game time = 2.600 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:47.790 -- System time = 55.671 -- Game time = 2.650 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:48.753 -- System time = 56.633 -- Game time = 2.700 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:49.716 -- System time = 57.597 -- Game time = 2.750 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:50.631 -- System time = 58.512 -- Game time = 2.800 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:51.566 -- System time = 59.447 -- Game time = 2.850 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:52.589 -- System time = 60.469 -- Game time = 2.900 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:53.511 -- System time = 61.392 -- Game time = 2.950 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:54.474 -- System time = 62.355 -- Game time = 3.000 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:55.404 -- System time = 63.284 -- Game time = 3.050 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:57.245 -- System time = 65.126 -- Game time = 3.100 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:58.214 -- System time = 66.095 -- Game time = 3.150 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:19:59.160 -- System time = 67.041 -- Game time = 3.200 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:00.097 -- System time = 67.977 -- Game time = 3.250 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:01.121 -- System time = 69.002 -- Game time = 3.300 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:02.063 -- System time = 69.944 -- Game time = 3.350 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:03.001 -- System time = 70.882 -- Game time = 3.400 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:03.945 -- System time = 71.826 -- Game time = 3.450 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:04.911 -- System time = 72.792 -- Game time = 3.500 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:05.845 -- System time = 73.726 -- Game time = 3.550 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:07.723 -- System time = 75.604 -- Game time = 3.600 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:08.668 -- System time = 76.549 -- Game time = 3.650 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:09.646 -- System time = 77.527 -- Game time = 3.700 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:10.658 -- System time = 78.539 -- Game time = 3.750 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:11.583 -- System time = 79.464 -- Game time = 3.800 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:12.574 -- System time = 80.455 -- Game time = 3.850 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:13.527 -- System time = 81.408 -- Game time = 3.900 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:14.442 -- System time = 82.323 -- Game time = 3.950 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:15.375 -- System time = 83.256 -- Game time = 4.000 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:16.342 -- System time = 84.223 -- Game time = 4.050 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:18.144 -- System time = 86.025 -- Game time = 4.100 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:19.125 -- System time = 87.006 -- Game time = 4.150 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:20.124 -- System time = 88.005 -- Game time = 4.200 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:21.103 -- System time = 88.984 -- Game time = 4.250 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:22.019 -- System time = 89.899 -- Game time = 4.300 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:22.953 -- System time = 90.833 -- Game time = 4.350 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:23.894 -- System time = 91.774 -- Game time = 4.400 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:24.886 -- System time = 92.767 -- Game time = 4.450 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:25.863 -- System time = 93.743 -- Game time = 4.500 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:26.823 -- System time = 94.703 -- Game time = 4.550 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:28.662 -- System time = 96.543 -- Game time = 4.600 -- Ratio = 0.048x
=== [Agent] -- Wallclock = 2024-07-24 08:20:29.609 -- System time = 97.490 -- Game time = 4.650 -- Ratio = 0.048x

Stopping the route, the agent has crashed:

Traceback (most recent call last):
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/leaderboard/scenarios/scenario_manager.py", line 188, in _tick_scenario
    ego_action = self._agent_wrapper()
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 147, in __call__
    return self._agent()
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 117, in __call__
    control = self.run_step(input_data, timestamp)
  File "/home/carla/anaconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/team_code/vad_b2d_agent.py", line 394, in run_step
    out_truck = all_out_truck[command]
IndexError: index 3 is out of bounds for axis 0 with size 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 415, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/leaderboard/scenarios/scenario_manager.py", line 161, in run_scenario
    self._tick_scenario()
  File "/home/carla/Bench2DriveZoo/Bench2Drive/leaderboard/leaderboard/scenarios/scenario_manager.py", line 196, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: index 3 is out of bounds for axis 0 with size 3

> Stopping the route

========= Results of RouteScenario_2127 (repetition 0) ------ FAILURE =========

╒═══════════════════════╤═════════════════════╕
│ Start Time            │ 2024-07-24 08:18:52 │
├───────────────────────┼─────────────────────┤
│ End Time              │ 2024-07-24 08:20:31 │
├───────────────────────┼─────────────────────┤
│ System Time           │ 99.12s              │
├───────────────────────┼─────────────────────┤
│ Game Time             │ 4.65s               │
├───────────────────────┼─────────────────────┤
│ Ratio (Game / System) │ 0.047               │
╘═══════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤══════════╕
│ Criterion             │ Result  │ Value    │
├───────────────────────┼─────────┼──────────┤
│ RouteCompletionTest   │ FAILURE │ 32.71 %  │
├───────────────────────┼─────────┼──────────┤
│ OutsideRouteLanesTest │ SUCCESS │ 0 %      │
├───────────────────────┼─────────┼──────────┤
│ CollisionTest         │ FAILURE │ 1 times  │
├───────────────────────┼─────────┼──────────┤
│ RunningRedLightTest   │ SUCCESS │ 0 times  │
├───────────────────────┼─────────┼──────────┤
│ RunningStopTest       │ SUCCESS │ 0 times  │
├───────────────────────┼─────────┼──────────┤
│ MinSpeedTest          │ SUCCESS │ 231.85 % │
├───────────────────────┼─────────┼──────────┤
│ InRouteTest           │ SUCCESS │          │
├───────────────────────┼─────────┼──────────┤
│ AgentBlockedTest      │ SUCCESS │          │
├───────────────────────┼─────────┼──────────┤
│ Timeout               │ SUCCESS │          │
╘═══════════════════════╧═════════╧══════════╛

> Registering the route statistics
False
`

**Comment by zhiyuanzzz** [comment]
@Huren900 Hi, we only provide config and checkpoint of **VAD_base** on **Bench2Drive** dataset, other settings may be not supported yet.

**Comment by Huren900** [comment]
@zhiyuanzzz thanks for your reply!
But when i set the config as follow:

`TEAM_AGENT=leaderboard/team_code/vad_b2d_agent.py # TEAM_CONFIG=your_team_agent_ckpt.pth   # for TCP and ADMLP
TEAM_CONFIG=/home/carla/Bench2DriveZoo/adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py+/home/carla/Bench2DriveZoo/Bench2Drive/ckpts/VAD_base.pth # for UniAD and VAD
`
<img width="953" alt="企业微信截图_17219877298094" src="https://github.com/user-attachments/assets/1473be6c-dd67-41e5-aeff-c9b3f1931d0a">

May i should download vad_b2d_base.pth rather than use VAD_base.pth ?

**Comment by jiaxiaosong1002** [comment]
@Huren900 Of course.  All b2d related code, data, checkpoint are not directly compatible with nuScenes ones.
