### ISSUE TITLE
img numbers

### ISSUE THREAD

**Issue by xiaobh1519** [Thinklab-SJTU/Bench2DriveZoo#17]
I notice that you use 950 clips for training, how do you choose these clips, randomly or based on some rules? And could you please tell us how many images are there in these 1000 clips?

**Comment by jiaxiaosong1002** [comment]
@xiaobh1519 Hi, as stated in paper,  we select val set so that those 50 clips containing at least one scenario (44/50) and the weather distribution as uniform as possible.  We also make sure there are all object detection classes in the val set.
