### ISSUE TITLE
Dropout

### ISSUE THREAD

**Issue by swc-17** [Thinklab-SJTU/Bench2DriveZoo#18]
Hi, 
  Thanks for the great work. I wonder why the dropout is changed from 0.1 to 0 in VAD config file?

**Comment by jiaxiaosong1002** [comment]
@swc-17 Hi, we do the adjustment due to the intuition that Bench2Drive has much data than nuScenes and thus the overfitting would not be a big problem.  Since we use 1/10 epochs compared to nuScenes, we decide to remove dropout to ensure convergence.

**Comment by swc-17** [comment]
Thanks for your reply!
