### ISSUE TITLE
how to set the correct sensors' pose to evaluate model trained on nuscenes

### ISSUE THREAD

**Issue by RobotiX101** [Thinklab-SJTU/Bench2DriveZoo#19]
Is there any utils to support the coordinate transformation from nuscenes to carla?

**Comment by jiaxiaosong1002** [comment]
@RobotiX101 We suggest to read https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/CONVERT_GUIDE.md and its related code carefully to align the coordinate system.   Or you may consider post-process our pickle, which is already in the  mmdet3d v0.17 (BEVFormer coordinate system).
