### ISSUE TITLE
Question about training VAD

### ISSUE THREAD

**Issue by MWPony** [Thinklab-SJTU/Bench2DriveZoo#2]
When using multiple GPUs to train VAD, the following issues occur：
![1718783386203](https://github.com/Thinklab-SJTU/Bench2DriveZoo/assets/115352662/c29eac51-414a-49cb-afe2-68ab2d7220bf)

**Comment by jiaxiaosong1002** [comment]
@MWPony   Hi,  it might be related to python or argparase version. 

One workaround is to add both args:
![image](https://github.com/Thinklab-SJTU/Bench2DriveZoo/assets/81464843/a9aee369-0aad-4a3c-97b9-fd36ef25935c)
