### ISSUE TITLE
lidar2img的标定参数好像有问题

### ISSUE THREAD

**Issue by jacken3** [Thinklab-SJTU/Bench2DriveZoo#20]
代码定位: https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/vad_b2d_agent.py#L120-L123

**Comment by jiaxiaosong1002** [comment]
@jacken3 Good point! Similar to https://github.com/Thinklab-SJTU/Bench2Drive/issues/36    We have published a notice.

**Comment by jacken3** [comment]
对了，在复现uniAD闭环评测的时候还发现了一处疑似bug
代码定位：https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/uniad_b2d_agent.py#L361

**Comment by jiaxiaosong1002** [comment]
@jacken3 Yeah. It should be https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/vad_b2d_agent.py#L376. We may upload the old version of team code agent. We are glad to hear from your reproduced testing results for verification!

**Comment by jacken3** [comment]
可以加一个联系方式嘛，有一些关于闭环仿真的问题想和您讨论一下
