### ISSUE TITLE
Dataset Structure

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2DriveZoo#29]
Hi,

When I download and unzip the files for the Bench2Drive Base, I get a file structure of Town folders and then within these folders there are the anno, camera, expert_assessment, lidar, and radar folders. How are we supposed to restructure these folders/files? What should I put in folders v1 and maps? The expert_assessment folders contain .npz files. Am I supposed to put these files under maps?

**Comment by jayyoung0802** [comment]
You can use [visualize.py](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/visualize.py) to get a feel for how this data can be used.

**Comment by ymoghadd** [comment]
I am referring to the folder structure here: [DATA_PREP](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/DATA_PREP.md). How do I organize the Bench2Drive Base dataset to follow that hierarchy when it does not have that structure at all? Clearly, visualize.py won't help me? It's not a part of this repository anyway.
