### ISSUE TITLE
load pretrained checkpoint from torchvision seems not supported now.

### ISSUE THREAD

**Issue by Mollylulu** [Thinklab-SJTU/Bench2DriveZoo#3]
I use the pretrained `init_cfg` as defined in mmcv-based config, current code seems do not support to loading the checkpoint from torchvision. And I found the problem seems to lie in weight_init.py ?

```
init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')
```

**Comment by jiaxiaosong1002** [comment]
@Mollylulu  Yes. During merging of mmcv/mmdet/mmdet3d, we remove some functions for conciseness.  As such functions are not complex, you might write several lines to do that by yourself.

**Comment by Mollylulu** [comment]
sure, thanks for the reply :) I thought including such a function may facilitate the lib usage, considering installation.
