### ISSUE TITLE
ques about TEAM_CONFIG and TEAM_AGENT

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2DriveZoo#31]
hello，could you please show an example about how to set the TEAM_AGENT and TEAM_CONFIG in run_evaluation_debug.sh ?

For example , I set：
TEAM_AGENT=leaderboard/team_code_zoo/vad_b2d_agent.py
TEAM_CONFIG=leaderboard/team_code_zoo/vad_b2d_agent.py+Bench2DriveZoo/ckpts/vad_b2d_base.pth
and when bash `leaderboard/scripts/run_evaluation_debug.sh`
bug occurs:
AttributeError: 'ConfigDict' object has no attribute 'model'

I have no idea whether there is something wrong with TEAM_AGENT and TEAM_CONFIG setting or other problem.

the whole output :
"""
Failed to stop the agent:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 367, in _load_and_run_scenario
    self.agent_instance.setup(args.agent_config)
  File "/home/user/Bench2Drive/leaderboard/team_code_zoo/vad_b2d_agent.py", line 69, in setup
    self.model = build_model(cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
  File "/home/user/Bench2DriveZoo/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/user/Bench2DriveZoo/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 178, in _cleanup
    self.agent_instance.destroy()
  File "/home/user/Bench2Drive/leaderboard/team_code_zoo/vad_b2d_agent.py", line 445, in destroy
    del self.model
AttributeError: model
"""

**Comment by jayyoung0802** [comment]
Hi, we update run_evaluation_multi.sh, please pull latest code and refer  [run_evaluation_multi_uniad.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_uniad.sh)

**Comment by starlighttt123** [comment]
thanks！By the way, how to set `$PLANNER_TYPE` in `leaderboard/scripts/run_evaluation_multi.sh`？It seems to miss in this script, thanks again!

**Comment by starlighttt123** [comment]
> Hi, we update run_evaluation_multi.sh, please pull latest code and refer [run_evaluation_multi_uniad.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_uniad.sh)

thanks！By the way, how to set $PLANNER_TYPE in leaderboard/scripts/run_evaluation_multi.sh？It seems to miss in this script, thanks again!

**Comment by starlighttt123** [comment]
> Hi, we update run_evaluation_multi.sh, please pull latest code and refer [run_evaluation_multi_uniad.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_uniad.sh)

thanks，it works
