### ISSUE TITLE
Has anyone reproduced the VAD closed-loop eval results?

### ISSUE THREAD

**Issue by AvinsWang** [Thinklab-SJTU/Bench2DriveZoo#36]
Has anyone reproduced the VAD experiment results?
(Bench2DriveZoo/adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py+Bench2DriveZoo/ckpts/vad_b2d_base.pth)

If so, could you please share the commit ID and the experiment result json. Cuz my results didn't match with the official's (39.42). Thanks in advance!

**Comment by jiaxiaosong1002** [comment]
@AvinsWang Please do not create duplicate issues. https://github.com/Thinklab-SJTU/Bench2Drive/issues/77
