### ISSUE TITLE
Assistance Needed with PID Controller on CARLA

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2DriveZoo#38]
Hello,

Thanks for your outstanding work!

I’m currently working with the VAD model in CARLA and encountered an issue with the PID controller. When the vehicle makes turns, there is a significant deviation between its actual trajectory and the predicted one. Could you please provide guidance on how to adjust or modify the PID controller to minimize this deviation?

Thank you for your assistance!

**Comment by jiaxiaosong1002** [comment]
@YiHuang108 We adopt the commonly used ones. You should learn PID from textbook and tune it.

**Comment by YiHuang108** [comment]
I'd like to ask if you have any textbook recommendations？

And, in addition, are the results of the VAD's closed-loop testing now available based on this commonly used version of the pid controller?

**Comment by jiaxiaosong1002** [comment]
@YiHuang108 Sorry, I am a CS background guy and could not give specific instructions.

Yes. Exactly. All models adopt the same PID controller.
