### ISSUE TITLE
what's the differences between the `mmcv` folder in this repo and the mmcv library?

### ISSUE THREAD

**Issue by Legend94rz** [Thinklab-SJTU/Bench2DriveZoo#4]
I want to know whether I should use the supplied `mmcv folder` instead of the installed one?

**Comment by jiaxiaosong1002** [comment]
@Legend94rz  Because in this way, you may use the latest Pytorch and other advanced packages like FlashAttention2/Deepspeed.

**Comment by Legend94rz** [comment]
I have alreay installed the latest pytorch, and install mmcv library via compile.
I worry about there may be some conflicts between the mmcv folder and my installed mmcv.
so, I want to know is it possible to use the installed mmcv, (e.g. mmcv==1.7.1) rather than the mmcv folder in this repo?
if yes, I could just ignore or remove the folder, or else I could uninstall the mmcv.

**Comment by jiaxiaosong1002** [comment]
No. You may not use another mmcv.  They are incompatible.
