### ISSUE TITLE
Question about desired_speed

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2DriveZoo#41]
Hi, dear author, thanks for your remarkable contribution. I noticed that in your PID controller implementation, you use the value 2.0 as bellow. I would appreciate it if you could clarify its significance. Is it related to the frequency (Hz), or is it being applied as a scaling factor?

```
        for i in range(num_pairs):
            # magnitude of vectors, used for speed
            desired_speed += np.linalg.norm(
                waypoints[i + 1] - waypoints[i]) * 2.0 / num_pairs
```

**Comment by jiaxiaosong1002** [comment]
@YiHuang108 It is the PID widely used in LBC, Transfuser, LAV, TCP, ect. We do not modify it at all. You may read the code to understand the logic.

**Comment by YiHuang108** [comment]
Thanks
