### ISSUE TITLE
Add new algo: VADv2

### ISSUE THREAD

**Issue by ruziniuuuuu** [Thinklab-SJTU/Bench2DriveZoo#44]
I just found that VAD v2 is now open-source. Are you guys considering adding it as soon as possible? Thanks!

**Comment by jiaxiaosong1002** [comment]
@ruziniuuuuu Feel free to implement it following the existing code. We are glad to refer to your repos if you have such plan.

**Comment by Wolfybox** [comment]
> @ruziniuuuuu Feel free to implement it following the existing code. We are glad to refer to your repos if you have such plan.

do you have any ideas how VADv2 generates the trajectory vocab?

**Comment by jiaxiaosong1002** [comment]
@Wolfybox No. We have not read their source code yet...
