### ISSUE TITLE
Town05 Long routes

### ISSUE THREAD

**Issue by yuchen-he** [Thinklab-SJTU/Bench2DriveZoo#45]
Hi, thanks for your great contributions.
I am trying to evaluate customized agent on Town05 Long based on B2D repo.
However, I could not find the routes_town05_long.xml file. Could you please share it?

**Comment by jiaxiaosong1002** [comment]
@yuchen-he You may check repos like TCP to find the Town05Long route. However, we have not tested Town05Long in any way and it may have lots of bugs.
