### ISSUE TITLE
B2D_VAD_Dataset

### ISSUE THREAD

**Issue by Zhihua-Hua** [Thinklab-SJTU/Bench2DriveZoo#46]
In your code, the ego_lcf_feat of the B2D_VAD_Dataset has been modified, where the first two dimensions and the eighth dimension differ from those in VAD.
https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/914b328f26b5534fd13b04d5fc644c8d82196d7b/mmcv/datasets/B2D_vad_dataset.py#L227
https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/914b328f26b5534fd13b04d5fc644c8d82196d7b/mmcv/datasets/B2D_vad_dataset.py#L232
https://github.com/hustvl/VAD/blob/3c2929fe36034b8881fd549394ee62f56b8ea44c/tools/data_converter/vad_nuscenes_converter.py#L508
Does it have any special meaning?

**Comment by jiaxiaosong1002** [comment]
@Zhihua-Hua Hi, good point! It is indeed a bug. However, since the feature is fed into MLP later, it would not be a big problem and you may fix the bug and re-train the model by yourself. We do not anticipate any major influence and thus we leave it here so that the public leaderboard is stable.
