### ISSUE TITLE
Wrong model weight link

### ISSUE THREAD

**Issue by Eden-Wang1710** [Thinklab-SJTU/Bench2DriveZoo#49]
Seems that the link of UniAD points to another model
![460abce904bdb572d7598b56ebb2e7ec](https://github.com/user-attachments/assets/63daa4c2-9337-44cb-80f9-fb9c1652e8ab)

**Comment by jiaxiaosong1002** [comment]
@Eden-Wang1710 Good point. Have fixed it.
