### ISSUE TITLE
VAD training time

### ISSUE THREAD

**Issue by itsbman** [Thinklab-SJTU/Bench2DriveZoo#5]
Hi, thank you for sharing this work!

I want to know how long does it typically take to train VAD for 60 epochs on the base dataset?

I'm training with 8 A6000 gpus and the eta is around 32 days

**Comment by jiaxiaosong1002** [comment]
@itsbman  As mentioned in paper, since the frequency of the dataset is 10Hz instead of 2Hz in nuScenes, there is lots of very similar samples.  Thus, we only train 1/10 epochs - 6 epochs.   The loss is normal.

**Comment by jiaxiaosong1002** [comment]
@itsbman Hi, you may modify the lr, epoch_number, and dropout as in the updated config file.

**Comment by itsbman** [comment]
That makes sense. Thanks
