### ISSUE TITLE
driveadapter eval 

### ISSUE THREAD

**Issue by SophieZhou** [Thinklab-SJTU/Bench2DriveZoo#50]
Thanks for your excellent work. In your paper, the closed-loop evaluation included driveadapter results, but I see the git web of driveadapter, its evaluation is based on carla 9.10 not 9.15. So in your paper, the results are based on 9.15?  Is the model of driveadapter  from driveadapter or trained by yourself?

Will you share the driveadapter models like VAD, UniVad trained by yourself?

**Comment by jiaxiaosong1002** [comment]
@SophieZhou A modified version of DriveAdapter is trained by us. No, we do not plan to share https://github.com/Thinklab-SJTU/Bench2Drive/issues/4
