### ISSUE TITLE
Estimated training time of UniAD and VAD on Bench2Drive-Base

### ISSUE THREAD

**Issue by kemaloksuz** [Thinklab-SJTU/Bench2DriveZoo#51]
Thanks for the great work. I think you used 8xA100 to train UniAD (tiny and base) and VAD (only base) by using 1 image/GPU. Please correct me if there is a mistake in this information. Also, how long should it take to train each of these models using this setting?

**Comment by jayyoung0802** [comment]
Hi @kemaloksuz , batch_size_per_gpu=1. As you train, you can see the time remaining in real time. And the details about training, you can refer to #5.
