### ISSUE TITLE
In the VAD training data, are there any routes designed to simulate drifting off course and then correcting back?

### ISSUE THREAD

**Issue by iuhiyuh** [Thinklab-SJTU/Bench2DriveZoo#52]
I noticed that in CARLA, VAD shows strong lateral correction ability, so I’m curious—does that mainly come from the data or is it more due to the imitation learning loss?

**Comment by jiaxiaosong1002** [comment]
@iuhiyuh  Not sure. Maybe data and imitation learning leads to Lane Keep characteristic.
