### ISSUE TITLE
question about ground truth ego state

### ISSUE THREAD

**Issue by robosuite** [Thinklab-SJTU/Bench2DriveZoo#54]
I have a question about the ground-truth ego state difference used in baseline TCP and VAD. It seems that TCP uses anno['x'],anno['y'] and anno['theta'], which is obtained by GPS (does it contain noise in annotation?) while VAD uses world2lidar and does some transformation to get the current and future state of the ego car. I find the values are different so I feel confused. Could you explain a bit?
Also, is it possible to construct sensor_infos['LIDAR_TOP']['world2lidar'] = world2lidar from x, y, and theta?

**Comment by jiaxiaosong1002** [comment]
@robosuite All code is written to follow this simple rule: for model inputs, it should be the noisy one to avoid train-val gap;  for labels, it should be the accurate one to avoid misleading gradient signals.

**Comment by 353xiong** [comment]
Just adding some noise?
There are many differences between them.
diff【x， y, distance】
diff: 2.1069997410202177 0.5875077126847827 2.187375875592343
diff: 1.262050104839318 0.6898723156646156 1.4382956160141047
diff: 1.5778646530909555 0.1953788743885525 1.5899150191224622
diff: 0.8692853296158773 0.9911667161559308 1.3183582379234848
diff: 0.9871166957871083 0.8836832148545 1.3248756150360843
diff: 2.0252845289364814 0.006701403705847042 2.0252956159437794
diff: 1.594730762844165 -0.0004164529409536044 1.5947308172210708
diff: 0.7022307996110158 0.21033862471722387 0.7330555456241087
diff: 2.04589210037102 -0.9277512883791132 2.2464186919293674
diff: 1.8681063978183374 1.0516565427360547 2.1437824044080025
diff: 1.446793544278762 0.24725844378735928 1.4677698381527156
diff: 1.7285897767767437 0.15471692979281215 1.735499912054618
diff: 1.0293818642262522 -0.3062466545270581 1.073971152222875
diff: 1.9237922776471805 0.29877844771453965 1.9468552304559361
diff: 1.921782228194843 -0.4637252010534212 1.9769390467835803
diff: 1.5173163863162245 0.18932552941350878 1.529082460912894
diff: 0.8250099241831776 1.2462638404167592 1.4945952411710208
diff: 1.1364537570109405 1.1405284269048934 1.6100721208698798
diff: 1.655906857752143 -0.5344070199489579 1.7400052829004002
diff: 1.1047793801496937 0.8982434058734725 1.4238604900056455
diff: 0.7773287042139145 0.7044757704661606 1.0490595910475125
diff: 1.278219085209912 1.099809846890821 1.686246046433579
diff: 1.8434362755006077 -0.9708419877661072 2.0834566151089393
diff: 1.6208656859550956 -0.045793610079272185 1.6215124503471365
diff: 1.616028707757323 1.0517443690041546 1.9281377030771818
diff: 1.396496241732848 0.8120888950161316 1.615453535878544
diff: 0.8177673329269055 0.6552864782934193 1.047923556103486
diff: 2.0484907915872554 0.8171742746444579 2.205467823015896
diff: 0.7932451040610431 0.6724777249301042 1.039934654506707
diff: 2.0921773054558344 0.30742772794928896 2.1146436308221057
diff: 1.0689914471829525 0.8860291777400562 1.3884489252244834
diff: 2.0164953896289717 -0.029086639097840816 2.016705156677323
diff: 1.7709135777931806 -0.2113591613715471 1.7834818740620626
diff: 1.065676182425932 0.6025645679228546 1.2242343665760917
diff: 1.6936111999509649 0.9042780168902027 1.9199056300845168
diff: 1.3043941261996679 -0.3827164341855678 1.3593807065939663
diff: 0.6031675413601079 0.4934594557817036 0.7793030972931986
diff: 2.017867581213295 -0.008841491763632803 2.0178869510674278
diff: 0.6567315012387098 0.9672699494403787 1.1691481599051687
diff: 0.7267453641284192 1.165044418738944 1.3731304824804205
diff: 1.2435554635067092 1.0749097722791703 1.6437339229202041
diff: 0.6585821010796735 0.6382874797609475 0.917137552759726
diff: 1.4027168295745014 0.29508261742557806 1.4334183810312573
diff: 1.1604646348655479 -0.09033316721524898 1.163975192979974
diff: 0.5834862582216829 -0.1906399485142174 0.6138402100734717
diff: 0.8635434204811645 0.19656702102838608 0.8856330124900964
diff: 1.8937501258496923 0.529876731722652 1.966483890088298
diff: 1.129083869761189 -0.7774218441691119 1.3708446698098966
diff: 2.114662763469596 1.0516583087837716 2.361733219827932
diff: 1.2204697073905209 0.6626414862757883 1.3887548545339776
diff: 1.3129240716250479 0.18194313034291554 1.3254708297550244
diff: 2.290594289908313 -0.07340379531251529 2.2917701276800972
diff: 1.2276223481246689 0.737225664329344 1.4319770632803337
diff: 1.6592248673478025 -0.2537117839938219 1.6785103007615594
diff: 1.487456114206907 -0.5445905807937379 1.5840153384297677
diff: 1.4983532283852128 0.4538645717284453 1.5655846979587642
diff: 1.6060301678523956 0.004337913042036234 1.6060360262277913
diff: 2.2192149756438084 0.6220809129972622 2.304755902571302
diff: 0.7543637225987823 0.43412984327278537 0.8703639162977436
diff: 0.6724787105708856 0.1911096606099818 0.699106943571256
diff: 1.4488502074384542 0.8116166080562834 1.6606891467301272
diff: 1.5879931339786708 1.0061461889399652 1.8799075368437186
diff: 1.0735897990082321 -0.6712237213450862 1.2661502046087905
diff: 0.22302855038037706 -0.2944915966863846 0.3694144485583483
diff: 0.9549606496275374 0.8922337613630589 1.3069165724150567
diff: 1.0837945180371662 0.9217395964924435 1.4227489030287341
diff: 1.4399603732756532 0.5875379882381822 1.5552127713683195
diff: 0.2335969140351608 -0.2380043945977377 0.3334870463670005
diff: 2.851525660136531 0.45427061438022065 2.8874833993473388
diff: 1.1593394503336185 0.2966498922687606 1.1966909039860394
diff: 1.2248355828091917 0.47232625064862077 1.3127506587190563
diff: 1.3053999972194106 0.17253893270662957 1.3167531416480387
diff: 1.3371966996812716 -1.0094971526796144 1.6754639700413536
diff: 0.5476280590050919 0.1915476456115357 0.5801611772163033
diff: 1.6233161826382911 -0.3894961808064181 1.6693899196048056
diff: 1.0039815250136144 -0.36173558283462626 1.0671605007951566
diff: 1.3743402672253069 0.33567496042905987 1.414739852119809
diff: 1.6523158881743711 -0.5779030151416009 1.7504627071786518
diff: 1.859902707149331 0.8382917625376649 2.04009096836389
diff: 1.1675145795097706 -0.009797025922125613 1.167555683933231
diff: 1.1886119632335976 -0.8781379306383315 1.4778107539085639
diff: 1.6116599690155908 0.7464880481402361 1.7761453380125047
diff: 2.0492749504376206 0.3865086360183341 2.0854056555519036
diff: 2.053550923044213 -0.2598704665160767 2.069928513959606
diff: 0.8102688789456352 0.8936104629674446 1.2062650271448256
diff: 0.9179136642278536 -0.9269466620862659 1.3045288840531952
diff: 0.9950872029714901 -0.815745189413974 1.2867162684794438
diff: 2.1363687979433053 -0.04292522091509454 2.136799994247551
diff: 0.9733581279260761 -0.33798466051939613 1.0303687087378803
diff: 0.7710487221463609 -1.023917349902149 1.2817655290083971
diff: 0.6474783994417521 -0.17787530810255703 0.67146697832152
diff: 0.6738586943622522 -0.3564209525238766 0.7623132134271495
diff: 1.6875633013539755 -0.7559456231929289 1.8491413362156162
diff: 1.3325304990371478 -0.37913583770750847 1.385417451275378
diff: 3.0142259727167584 0.021039563446720422 3.0142994008277144
diff: 1.6784626493172254 -0.20496059468223393 1.6909304274645645
diff: 0.18501827709815188 0.2664049698059898 0.32435069107017306
diff: 1.2583797196243722 -0.8325795248365466 1.5088764641079677
diff: 1.9441345176053346 0.43601777518051676 1.9924282980368189
diff: 1.3958446944052412 -0.2965725897975062 1.4270030525259787
diff: 1.3624389126644019 -0.6308914007440762 1.5014205774115994
diff: 1.8642147269943052 -0.4420240900362842 1.9159023577716212
diff: 1.6861125331329276 -0.39542763871395437 1.7318598360857127
diff: 2.0578737997507233 -1.3645479296628764 2.4691771155686104
diff: 2.108341635820352 -0.999383582739938 2.333210663181478
diff: 2.281499690556757 -0.06433115470099438 2.282406479020716
diff: 1.0903513325661152 -1.1626078631443306 1.5939018388450807
diff: 1.3381961957866224 0.4405069918038862 1.408834790969437
diff: 0.8169563066967385 -0.7953039694230029 1.1401429782406942
diff: 1.490378090208651 -1.1501000157686576 1.8825400123357412
diff: 1.3633031648571432 0.0672967503342079 1.364963139397928
diff: 1.123613342120052 -0.3393906781575424 1.1737516666699261
diff: 1.6115978434572753 0.4044556651124367 1.6615751545078195
diff: 1.2786205773329584 -0.527025644173591 1.3829774439215763
diff: 1.6758091987690023 1.2549117113039756 2.0935949641338647
diff: 0.5902725358218959 -0.6263635748282468 0.8606700845371774
diff: 0.940914417034719 0.41763116541551426 1.0294346654888331
diff: 1.7277431362188054 -0.17749535228995228 1.7368364761357724
diff: 1.8308105418791456 -0.1787769033899167 1.8395185297902
diff: 1.4025021028551237 0.501404979497238 1.4894358334542879
diff: 1.5430281278611346 0.5116165574081606 1.625634431594267
diff: 1.9645772180954282 -0.01695850803571375 1.9646504108503295
diff: 1.6010869127001115 0.03081799440042232 1.6013834802440166
diff: 0.7714200971656737 0.6677132364429781 1.020259737729689
diff: 1.1656788462355507 0.9097251612920445 1.4786504122506041
diff: 0.8872595911489043 0.15110593364806846 0.9000347689224985
diff: 1.183788083633317 -0.3235051875890349 1.2271959229679905
diff: 1.1305793837530018 1.7419279507712417 2.0766614381370436
diff: 1.543034758501335 0.34468379639474733 1.5810639409715121
diff: 1.426243782051415 -0.23736140169694409 1.4458602148395476
diff: 1.5202838517770942 0.13382993466257176 1.5261629799552818
diff: 2.121160404719376 1.0077874005955891 2.348394538264063
diff: 1.6871766597264468 0.6455805598825464 1.8064715166378773
diff: 1.3861066540362117 0.7953090561904901 1.5980638758266426
diff: 1.0056182422729307 1.017328198071482 1.4304631109481527
diff: 2.044782119774709 1.0470575837607612 2.2972730575752798
diff: 1.655731372617538 1.151613494834237 2.016844074229409
diff: 0.4848576120762118 0.05817523047699069 0.4883351937238369
diff: 0.8270459149450744 0.5600113795962898 0.9988081350813454
diff: 1.8115582300081314 1.530238904600992 2.371365498160214
diff: 0.4595563300320009 0.6572111960049369 0.8019467417645145
diff: 0.8570364178578984 0.439586665645038 0.9631966871556509
diff: 0.6202380750705743 0.253021129174158 0.6698618973906616
diff: 1.9382496603006985 0.024750309594310238 1.9384076773168195
diff: 1.5510275186156832 0.22507794299053785 1.567273570224412
diff: 1.583587498206498 0.16377952625498438 1.5920342639831035
diff: 1.410166273120467 0.8182241836029789 1.6303557073470896
diff: 1.3265139174241085 1.4128162509068716 1.9379599923492752
diff: 1.5226687464021325 0.6793119215144543 1.6673286412646735
diff: 1.2625594012959027 -0.525803910391005 1.3676717420430753
diff: 0.7595745983890083 0.8482116750519708 1.1386029229772308
diff: 1.582202361508962 0.1771893866798564 1.5920930850664856
diff: 1.9552879230500366 -0.07440332892383594 1.9567030222750397
diff: 1.2533357725985752 0.3899949726255727 1.3126106191664337
diff: 1.6843994769171786 1.221426675316252 2.0806452655397503
diff: 1.9212868983418048 -0.15294735310999386 1.9273651025592493
diff: 0.2815378058157876 0.2682206619383578 0.38885197645661895
diff: 2.5890478673993584 0.6208955151878399 2.6624575302651383
diff: 2.531175527050209 0.5589290892248755 2.5921518619709865
diff: 1.0837329372586737 1.0439662011649489 1.5047732415464088
diff: 2.0523560851872844 1.287710506624535 2.4228833750877263
diff: 0.6563230047840989 0.37783080737244745 0.7573083953110145
diff: 0.8244747777125667 0.05736210109171225 0.8264678273991324
diff: 1.656405228205358 -0.04568768895751418 1.657035197256933
diff: 0.6930420717083052 1.285946525923464 1.4608099741897869
diff: 1.546529709418337 0.0671578010687881 1.5479871809410957
diff: 1.4585927410532804 0.5761721381031748 1.5682688280329065
diff: 1.7204173924851602 0.09785641037888126 1.723198155006463
diff: 2.4415098175961703 1.3900332928415082 2.8094773080817523
diff: 1.27908032421783 0.6378671447628221 1.4293078640268737
diff: 0.4721223117749105 0.4111471551686918 0.6260522825443527
diff: 2.1360489020046316 0.3637700629342362 2.166802614554997
diff: 1.7883389428604914 1.1580456504989343 2.130545916705594
diff: 1.6233073285904993 -0.15677566534759535 1.630860292085378
diff: 1.0759907515546274 0.6831790861560876 1.2745547305597194
diff: 1.4881295320703884 0.7316816904758525 1.6582785050761633
diff: 1.6207031638555236 0.2506950847218832 1.6399776738830978
diff: 1.513579970654746 -0.07936356017853541 1.5156592302531045
diff: 1.6839626058667818 0.5549149617190778 1.7730371323515275
diff: 1.3796490627812545 0.16074899691011524 1.388982280823194
diff: 1.0577817959797358 -0.9590487929053779 1.4278224382182043
diff: 0.26778962570961085 -0.041265315008786274 0.2709503826542192
diff: 1.1383062491302098 0.3132696601378484 1.1806265272183962
diff: 1.554567988809822 -0.061114482482480526 1.5557688169523507
diff: 1.472089378154351 1.055232090773643 1.811232150408494
diff: 1.0738870594909713 0.4604230218774319 1.1684274798278715
diff: 1.1190939563341544 0.2996405599933496 1.1585144575259985
diff: 2.090642313350372 -0.4188648433828348 2.132189728751436
diff: 0.4238852519060856 0.208943038106554 0.4725842781522493
diff: 2.0813704733511713 -0.16729798957203457 2.0880832513702425
diff: 1.0885480384145012 -0.22149949637241662 1.1108550125148162
diff: 1.1046206365053877 0.1258964298549472 1.1117718568320523
diff: 1.566814409983408 -0.2572855335620261 1.587798236902898
diff: 1.4261685621270317 0.33304252698599157 1.4645388668043946
diff: 1.0487023398075053 -0.3469856649026042 1.1046156114982435
diff: 1.7108503029571693 -0.14244105123634654 1.7167697027283402
diff: 2.0356261661102053 0.5476692182101033 2.108012206019547
diff: 2.012953312523223 0.46673086725331814 2.066353972785217
diff: 1.090870841454489 0.3208272593683432 1.1370705004921318
diff: 0.48450388447326986 0.6979790977602534 0.8496580694490607
diff: 1.556643475483952 0.4226047252323042 1.6129890463222087
diff: 1.4759181370666283 0.25618493998899794 1.4979870062184764
diff: 1.633460664172162 0.7147535237618285 1.7829936458461404
diff: 1.178439566836687 -0.10931778833582939 1.1834991303473255
diff: 0.41782599109887997 0.29926300430179253 0.5139425109693652
diff: 2.1094701189231273 0.6830369877043267 2.2172964865352927
diff: 0.6875611394943917 0.06910598336435214 0.6910252943847862
diff: 0.9852315192983951 0.08192543168115662 0.9886318440021886
diff: 2.024105541238441 0.13587201210339117 2.028660751763386
diff: 2.0905260205045124 0.3933916588739521 2.1272179107176665
diff: 1.8181226330739264 -0.38605003511111136 1.858656648901286
diff: 1.816299953623684 1.3975026059288211 2.291715308477744
diff: 1.355584525264021 0.37330175428724033 1.4060453779623232
diff: 2.159298288184118 0.7049057311860452 2.271444735672386
diff: 2.017955488134021 0.23226186832653184 2.031277905056013
diff: 0.5369125385427651 1.5171990608951091 1.6093999081724335
diff: 1.5727868646429215 0.28569111399701796 1.5985236733342951
diff: 1.3843426839980566 -0.08702663447274972 1.387075449226392
diff: 1.571939463425224 -0.053716071268354426 1.5728569842760936
diff: 1.357851096185641 -0.19948706203922484 1.372426569013289
diff: 1.9534026084616016 0.5484900630381162 2.0289463028863395
diff: 1.6308527737348868 0.13646059354687168 1.636551943321671
diff: 1.1794596529221053 0.3495761659760319 1.2301742025784947
diff: 0.8263951474227724 0.37259609736065613 0.906508020622155
diff: 2.1294520324497626 -0.1869084414374811 2.137639053719082
diff: 0.5453362609246142 -0.2967499528049302 0.6208479459327921
diff: 1.9356521341924235 -0.6264199487259248 2.0344903874841664
diff: 1.8591102798870907 1.5383591059362516 2.4130561061854405
diff: 0.4795449118964825 -1.1056542351680037 1.2051699507831866
diff: 1.8313052951111786 0.6690798131785414 1.949704305864167
diff: 1.1084615194679373 -0.30537195617944235 1.1497560488042788
diff: 1.08837683180991 -0.09238935470511933 1.092291133756658
