### ISSUE TITLE
About Training and Evaluation of the Think2Drive Model

### ISSUE THREAD

**Issue by Mollylulu** [Thinklab-SJTU/Bench2DriveZoo#55]
Hi~ Thanks for your great work! As I am new to this area, I would greatly appreciate your guidance on how to train and evaluate your **Think2Drive** Model. Any assistance or resources you can provide would be highly valuable.

Thank you for your time and support!

**Comment by jiaxiaosong1002** [comment]
@Mollylulu No. We do not plan to open source Think2Drive.
