### ISSUE TITLE
Is there any wrong for introduction of usage?

### ISSUE THREAD

**Issue by wsonnnn** [Thinklab-SJTU/Bench2DriveZoo#56]
I found that train of VAD given in TRAIN_EVAL.md "./adzoo/vad/dist_train.sh ./adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py ./ckpts/vad_b2d_base.pth 1" didn't work, maybe the right is "./adzoo/vad/dist_train.sh ./adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py 1"?
By the way, the link Get start/Prepare Dataset in Readme.md is setted wrongly.

**Comment by jiaxiaosong1002** [comment]
@wsonnnn Thanks for your advice! Indeed all your points are correct. We have updated it.
