### ISSUE TITLE
Duplicate NameMapping in VAD dataset

### ISSUE THREAD

**Issue by Beanocean** [Thinklab-SJTU/Bench2DriveZoo#57]
https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/498c1f799dd90faf840dedb3f0d3234ec2e567db/adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py#L46-L49

It appears that the key `SM_VolkswagenT2_2021_Parked.SM_VolkswagenT2_2021_Parked` in the `NameMapping` has been mapped to different categories?

**Comment by jayyoung0802** [comment]
Hi @Beanocean, thanks for your finding, this value will be updated to the van(correct label), so it will not influence the results.
