### ISSUE TITLE
BEVFormer-Tiny

### ISSUE THREAD

**Issue by zxzxsx** [Thinklab-SJTU/Bench2DriveZoo#58]
If I want to train BEVFormer-Tiny, approximately what level of computing resources and VRAM will I need?

**Comment by jayyoung0802** [comment]
It is similar to training BEVFormer-Tiny on Nuscense, 4090/A100 is all you need.

**Comment by zxzxsx** [comment]
What about BEVFormer-base? Are 4 * 3090 enough?
