### ISSUE TITLE
How can I configure the VAD related environment on A100 GPU and CUDA 11.8?

### ISSUE THREAD

**Issue by JesseTowne** [Thinklab-SJTU/Bench2DriveZoo#59]
Thanks to the author's excellent work, I noticed that you configured the virtual environment on top of CUDA 11.8 and started the experiment on A100. But there is no mention of version numbers of dependent libraries such as MMCV, MMDetection, MMDetection3D etc. in [INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md), which is confusing. May I ask how the environment was configured to adapt to A100 GPU and CUDA 11.8 when training VAD?

**Comment by jayyoung0802** [comment]
Refer to [issue](https://github.com/Thinklab-SJTU/Bench2Drive/issues/52#issuecomment-2550311842).
