### ISSUE TITLE
VAD closed-loop performence on CARLA 

### ISSUE THREAD

**Issue by turboxin** [Thinklab-SJTU/Bench2DriveZoo#6]
Hi，thanks for opensourcing this great work!  I'm wondering how's the VAD closed-loop performence on CARLA of your implementation compared with official VAD results.

**Comment by jiaxiaosong1002** [comment]
@turboxin  Hi, since the benchmark and training set are very different, it is hard to conduct direct comparison.

**Comment by turboxin** [comment]
@jiaxiaosong1002 Hi xiaosong, thank your for your reply. Could you please explain how the  benchmark and training set are different detaily? I'm very appreciated if you could help me clarify this out~

**Comment by jiaxiaosong1002** [comment]
@turboxin Please refer to our paper and VAD's paper for details
