### ISSUE TITLE
the x and y in anno are derived from GPS？

### ISSUE THREAD

**Issue by feng-7** [Thinklab-SJTU/Bench2DriveZoo#60]
From the data_collect.py code, it seems that the x and y in anno are derived from GPS. However, the data_collect script does not explicitly call the gps_to_location function to generate the pos field. Could you kindly confirm if the x and y in anno are indeed generated by calling the gps_to_location function?

**Comment by jayyoung0802** [comment]
Hi @feng-7 , there are two types of x and y coordinates: one is derived from the CARLA actor, which is used for perception labeling but cannot be used for evaluation; the other comes from GPS data, which can be used for evaluation.
