### ISSUE TITLE
Upload fixed UniAD checkpoints

### ISSUE THREAD

**Issue by dmholtz** [Thinklab-SJTU/Bench2DriveZoo#61]
Dear Bench2Drive Team,

from reading the [news section](https://github.com/Thinklab-SJTU/Bench2Drive?tab=readme-ov-file#news-), I learned that you found a few bugs in the UniAD model code which had significant impacts on the model performance. However, the model checkpoints available at [huggingface](https://huggingface.co/rethinklab/Bench2DriveZoo/tree/main) do not seem to reflect the latest bugfixes since they date back to Jun 5 this year.

Could you please upload the checkpoints at huggingface of both BEVFormer UniAD to ensure that the latest numbers from the paper can be reproduced by the community?

I would also be very interested in the intermediate checkpoint of the UniAD stage1 for both the base and the tiny config and would kindly ask to provide them as well.

Thank you very much for your efforts and the pioneering work in enabling closed-loop benchmarks on challenging routes in CARLA!

**Comment by jiaxiaosong1002** [comment]
@dmholtz Hi, the update does not influence the training process. In other words, the original bug is at inference stage. Thus, the checkpoint does not need to be updated.

**Comment by dmholtz** [comment]
@jiaxiaosong1002 Understood, thank you very much for your reply.
