### ISSUE TITLE
About Collecting Open-loop Test Data (Base Dataset) with Route Configuration Files in XML Format

### ISSUE THREAD

**Issue by XinyuXia97** [Thinklab-SJTU/Bench2DriveZoo#63]
I need to gather a base dataset consisting of 1,000 open-loop test data entries, which should include route configuration files in XML format. Would it be possible for you to share the route configuration files (XML format) used in your research?

**Comment by jiaxiaosong1002** [comment]
@XinyuXia97 Sorry. No.
