### ISSUE TITLE
Question on command near in close-loop running.

### ISSUE THREAD

**Issue by jcuic5** [Thinklab-SJTU/Bench2DriveZoo#64]
Thanks for the great work. In terms of the code in close-loop running, I was wondering why route planner's routes[1] is returned as agent's near command. Isn't it the target's point's command itself (i.e., next command), not the comand towards it? In another word, why isn't route[0]'s command used for command near. Appreciate it for the explanation

https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/498c1f799dd90faf840dedb3f0d3234ec2e567db/team_code/planner.py#L118

**Comment by jayyoung0802** [comment]
Hi @jcuic5, refer to #34.
